import type { Member, Reservation, Pass, DailySales, RentalItem, AuditLog, User, Expense, StaffMember, ScheduleEntry } from '../types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'admin',
    name: '관리자',
    role: 'super_admin',
    email: 'admin@lounge.com',
    isActive: true,
    lastLogin: '2026-03-11T09:00:00',
    createdAt: '2024-01-01T00:00:00',
  },
  {
    id: 'u2',
    username: 'manager1',
    name: '김매니저',
    role: 'manager',
    email: 'manager@lounge.com',
    isActive: true,
    lastLogin: '2026-03-11T08:30:00',
    createdAt: '2024-06-01T00:00:00',
  },
  {
    id: 'u3',
    username: 'staff1',
    name: '이스태프',
    role: 'staff',
    email: 'staff@lounge.com',
    isActive: true,
    lastLogin: '2026-03-10T17:00:00',
    createdAt: '2025-01-01T00:00:00',
  },
];

export const mockMembers: Member[] = [
  {
    id: 'm1',
    name: '김지은',
    phone: '010-1234-5678',
    email: 'jieun@email.com',
    job: '프리랜서 디자이너',
    workMood: '집중형',
    workersJourney: '독립 작업',
    visitCount: 15,
    interests: '디자인, 브랜딩',
    programParticipation: '워크앤리듬 챌린지',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'active',
    registeredAt: '2025-06-15',
    notes: '단골 고객, 오전 시간대 선호',
    passIds: ['p1'],
  },
  {
    id: 'm2',
    name: '박서준',
    phone: '010-2345-6789',
    email: 'seojun@email.com',
    job: '스타트업 대표',
    workMood: '협업형',
    workersJourney: '팀 미팅',
    visitCount: 8,
    interests: '네트워킹, 비즈니스',
    programParticipation: '',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: false,
    membershipStatus: 'active',
    registeredAt: '2025-09-20',
    notes: '워커스룸 주 이용',
    passIds: ['p2'],
  },
  {
    id: 'm3',
    name: '이하늘',
    phone: '010-3456-7890',
    email: 'haneul@email.com',
    job: '콘텐츠 크리에이터',
    workMood: '자유형',
    workersJourney: '콘텐츠 제작',
    visitCount: 22,
    interests: '영상, 사진',
    programParticipation: '편지 프로젝트',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'active',
    registeredAt: '2025-03-10',
    notes: '메이커스룸 자주 이용',
    passIds: ['p3'],
  },
  {
    id: 'm4',
    name: '정우성',
    phone: '010-4567-8901',
    email: 'woosung@email.com',
    job: '개발자',
    workMood: '집중형',
    workersJourney: '코딩 작업',
    visitCount: 5,
    interests: '기술, 개발',
    programParticipation: '',
    smsConsent: false,
    privacyConsent: true,
    marketingConsent: false,
    membershipStatus: 'active',
    registeredAt: '2025-12-01',
    notes: '',
    passIds: [],
  },
  {
    id: 'm5',
    name: '최민서',
    phone: '010-5678-9012',
    email: 'minseo@email.com',
    job: '작가',
    workMood: '집중형',
    workersJourney: '글쓰기',
    visitCount: 30,
    interests: '글쓰기, 독서',
    programParticipation: '워크앤리듬 챌린지, 편지 프로젝트',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'active',
    registeredAt: '2024-11-05',
    notes: 'VIP 단골 고객',
    passIds: ['p4', 'p5'],
  },
  {
    id: 'm6',
    name: '한소희',
    phone: '010-6789-0123',
    email: 'sohee@email.com',
    job: '마케터',
    workMood: '협업형',
    workersJourney: '기획 작업',
    visitCount: 2,
    interests: '마케팅, 브랜딩',
    programParticipation: '',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'dormant',
    registeredAt: '2025-10-20',
    notes: '3개월 이상 미방문',
    passIds: [],
  },
  {
    id: 'm7',
    name: '윤서연',
    phone: '010-7890-1234',
    email: 'seoyeon@email.com',
    job: '그래픽 디자이너',
    workMood: '자유형',
    workersJourney: '디자인 작업',
    visitCount: 1,
    interests: '디자인, 일러스트',
    programParticipation: '',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'active',
    registeredAt: '2026-03-05',
    notes: '신규 가입',
    passIds: [],
  },
  {
    id: 'm8',
    name: '강도현',
    phone: '010-8901-2345',
    email: 'dohyun@email.com',
    job: '영상 편집자',
    workMood: '집중형',
    workersJourney: '영상 편집',
    visitCount: 2,
    interests: '영상, 음악',
    programParticipation: '',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: true,
    membershipStatus: 'active',
    registeredAt: '2026-03-08',
    notes: '',
    passIds: [],
  },
  {
    id: 'm9',
    name: '임채원',
    phone: '010-9012-3456',
    email: 'chaewon@email.com',
    job: '프리랜서 작가',
    workMood: '집중형',
    workersJourney: '글쓰기',
    visitCount: 1,
    interests: '글쓰기',
    programParticipation: '',
    smsConsent: true,
    privacyConsent: true,
    marketingConsent: false,
    membershipStatus: 'active',
    registeredAt: '2026-03-10',
    notes: '',
    passIds: [],
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'r1',
    date: '2026-03-11',
    time: '10:00',
    reserverName: '김지은',
    phone: '010-1234-5678',
    email: 'jieun@email.com',
    visitorName: '김지은',
    visitorPhone: '010-1234-5678',
    product: '1DAY',
    seat: 'A-3',
    paymentAmount: 36000,
    paymentMethod: '신용카드',
    checkInTime: '09:55',
    checkOutTime: null,
    stayDuration: null,
    source: 'naver',
    visitPath: '네이버 플레이스 - 검색 목록',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: ['HDMI-C 컨버터'],
    guideTime: '10:00',
    guideStaff: '이스태프',
    program: '커넥트라이브러리',
    isRevisit: true,
    membershipJoined: true,
    notes: '',
    status: 'checked_in',
  },
  {
    id: 'r2',
    date: '2026-03-11',
    time: '10:00',
    reserverName: '박서준',
    phone: '010-2345-6789',
    email: 'seojun@email.com',
    visitorName: '박서준',
    visitorPhone: '010-2345-6789',
    product: '워커스룸',
    seat: 'W-1',
    paymentAmount: 50000,
    paymentMethod: '네이버페이',
    checkInTime: '10:05',
    checkOutTime: null,
    stayDuration: null,
    source: 'naver',
    visitPath: '네이버 플레이스 - 업체명 검색',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: [],
    guideTime: '10:05',
    guideStaff: '김매니저',
    program: '디퍼스테이지',
    isRevisit: true,
    membershipJoined: true,
    notes: '팀 미팅 2명',
    status: 'checked_in',
  },
  {
    id: 'r3',
    date: '2026-03-11',
    time: '12:00',
    reserverName: '이하늘',
    phone: '010-3456-7890',
    email: 'haneul@email.com',
    visitorName: '이하늘',
    visitorPhone: '010-3456-7890',
    product: '4시간',
    seat: 'B-5',
    paymentAmount: 18000,
    paymentMethod: '신용카드',
    checkInTime: null,
    checkOutTime: null,
    stayDuration: null,
    source: 'naver',
    visitPath: '네이버 플레이스 - 검색 목록',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: [],
    guideTime: '',
    guideStaff: '',
    program: '',
    isRevisit: true,
    membershipJoined: true,
    notes: '',
    status: 'confirmed',
  },
  {
    id: 'r4',
    date: '2026-03-11',
    time: '14:00',
    reserverName: '정우성',
    phone: '010-4567-8901',
    email: 'woosung@email.com',
    visitorName: '정우성',
    visitorPhone: '010-4567-8901',
    product: '4시간',
    seat: 'A-7',
    paymentAmount: 18000,
    paymentMethod: '신용카드',
    checkInTime: null,
    checkOutTime: null,
    stayDuration: null,
    source: 'walkin',
    visitPath: '인스타그램',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: [],
    guideTime: '',
    guideStaff: '',
    program: '',
    isRevisit: false,
    membershipJoined: false,
    notes: '워크인 방문',
    status: 'confirmed',
  },
  {
    id: 'r5',
    date: '2026-03-11',
    time: '10:00',
    reserverName: '최민서',
    phone: '010-5678-9012',
    email: 'minseo@email.com',
    visitorName: '최민서',
    visitorPhone: '010-5678-9012',
    product: '1DAY',
    seat: 'C-2',
    paymentAmount: 0,
    paymentMethod: '10회권',
    checkInTime: '10:02',
    checkOutTime: '18:30',
    stayDuration: 508,
    source: 'naver',
    visitPath: '네이버 플레이스 - 검색 목록',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: ['USB-C 케이블'],
    guideTime: '10:02',
    guideStaff: '이스태프',
    program: '워크앤리듬 챌린지',
    isRevisit: true,
    membershipJoined: true,
    notes: '',
    status: 'checked_out',
  },
  {
    id: 'r6',
    date: '2026-03-10',
    time: '10:00',
    reserverName: '한소희',
    phone: '010-6789-0123',
    email: 'sohee@email.com',
    visitorName: '한소희',
    visitorPhone: '010-6789-0123',
    product: '2시간',
    seat: 'A-1',
    paymentAmount: 12000,
    paymentMethod: '신용카드',
    checkInTime: '10:00',
    checkOutTime: '12:05',
    stayDuration: 125,
    source: 'walkin',
    visitPath: '지인 추천',
    isRefunded: false,
    refundAmount: 0,
    rentalItems: [],
    guideTime: '10:00',
    guideStaff: '이스태프',
    program: '',
    isRevisit: false,
    membershipJoined: false,
    notes: '',
    status: 'checked_out',
  },
];

export const mockPasses: Pass[] = [
  {
    id: 'p1',
    memberId: 'm1',
    memberName: '김지은',
    phone: '010-1234-5678',
    type: '종일 10회권',
    purchaseDate: '2026-01-15',
    totalUses: 10,
    remainingUses: 4,
    usageHistory: [
      { date: '2026-01-20' }, { date: '2026-01-25' }, { date: '2026-02-03' },
      { date: '2026-02-10' }, { date: '2026-02-17' }, { date: '2026-02-24' },
    ],
    status: 'active',
    notes: '',
  },
  {
    id: 'p2',
    memberId: 'm2',
    memberName: '박서준',
    phone: '010-2345-6789',
    type: '4시간 10회권',
    purchaseDate: '2026-02-01',
    totalUses: 10,
    remainingUses: 7,
    usageHistory: [
      { date: '2026-02-05' }, { date: '2026-02-12' }, { date: '2026-02-20' },
    ],
    status: 'active',
    notes: '',
  },
  {
    id: 'p3',
    memberId: 'm3',
    memberName: '이하늘',
    phone: '010-3456-7890',
    type: '종일 10회권',
    purchaseDate: '2025-12-01',
    totalUses: 10,
    remainingUses: 1,
    usageHistory: [
      { date: '2025-12-05' }, { date: '2025-12-10' }, { date: '2025-12-15' },
      { date: '2025-12-20' }, { date: '2025-12-27' }, { date: '2026-01-05' },
      { date: '2026-01-12' }, { date: '2026-01-20' }, { date: '2026-02-03' },
    ],
    status: 'active',
    notes: '잔여 1회 - 알림 필요',
  },
  {
    id: 'p4',
    memberId: 'm5',
    memberName: '최민서',
    phone: '010-5678-9012',
    type: '종일 10회권',
    purchaseDate: '2026-02-10',
    totalUses: 10,
    remainingUses: 6,
    usageHistory: [
      { date: '2026-02-15' }, { date: '2026-02-20' }, { date: '2026-02-28' },
      { date: '2026-03-05' },
    ],
    status: 'active',
    notes: '',
  },
  {
    id: 'p5',
    memberId: 'm5',
    memberName: '최민서',
    phone: '010-5678-9012',
    type: '무료이용권',
    purchaseDate: '2026-01-01',
    totalUses: 3,
    remainingUses: 1,
    usageHistory: [
      { date: '2026-01-10' }, { date: '2026-02-14' },
    ],
    status: 'active',
    notes: '단골 고객 혜택',
  },
];

export const mockDailySales: DailySales[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date(2026, 2, 30 - i);
  const dayOfWeek = date.getDay();
  const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
  const base = isWeekend ? 18 : 12;
  const totalVisitors = base + Math.floor(Math.random() * 8);
  const paidFullDay = Math.floor(totalVisitors * 0.3);
  const paid4Hours = Math.floor(totalVisitors * 0.15);
  const paid2Hours = Math.floor(totalVisitors * 0.1);
  const freeFullDay = Math.floor(totalVisitors * 0.2);
  const free4Hours = Math.floor(totalVisitors * 0.1);
  const free2Hours = totalVisitors - paidFullDay - paid4Hours - paid2Hours - freeFullDay - free4Hours;
  const newV = Math.floor(totalVisitors * (0.3 + Math.random() * 0.2));
  const revisitors = totalVisitors - newV;

  return {
    date: date.toISOString().split('T')[0],
    totalVisitors,
    freeFullDay,
    free4Hours,
    free2Hours,
    paidFullDay,
    paid4Hours,
    paid2Hours,
    naverBookings: Math.floor(totalVisitors * 0.7),
    walkinBookings: Math.floor(totalVisitors * 0.3),
    newVisitors: newV,
    revisitors,
    revisitRate: Math.round((revisitors / totalVisitors) * 100),
    totalRevenue: paidFullDay * 36000 + paid4Hours * 18000 + paid2Hours * 12000,
  };
});

export const mockRentalItems: RentalItem[] = [
  { id: 'ri1', name: 'HDMI-C 컨버터', totalQuantity: 11, availableQuantity: 9, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
  { id: 'ri2', name: 'USB 어댑터', totalQuantity: 3, availableQuantity: 2, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
  { id: 'ri3', name: 'USB-C 케이블', totalQuantity: 12, availableQuantity: 10, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
  { id: 'ri4', name: 'USB-라이트닝 케이블', totalQuantity: 16, availableQuantity: 15, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
  { id: 'ri5', name: '보조배터리', totalQuantity: 5, availableQuantity: 4, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
  { id: 'ri6', name: '담요', totalQuantity: 8, availableQuantity: 6, location: '리셉션 뒤 수납장', status: '정상', notes: '', purchaseLink: '' },
];

export const mockExpenses: Expense[] = [
  {
    id: 'EXP001',
    date: '2026-02-03',
    category: '운영비',
    itemName: '유튜브 프리미엄',
    purpose: '라운지 BGM 재생용',
    vendor: 'Google',
    supplyAmount: 13545,
    tax: 1355,
    totalAmount: 14900,
    paymentMethod: '카드 결제(온라인)',
    notes: '월 정기결제',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP002',
    date: '2026-02-05',
    category: '운영비',
    itemName: '우드 나무 포크',
    purpose: 'F&B 비품',
    vendor: '쿠팡',
    supplyAmount: 92045,
    tax: 9205,
    totalAmount: 101250,
    paymentMethod: '쿠팡',
    notes: '',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP003',
    date: '2026-02-07',
    category: 'F&B',
    itemName: '스니커즈',
    purpose: '판매용 스낵',
    vendor: '쿠팡',
    supplyAmount: 21645,
    tax: 2165,
    totalAmount: 23810,
    paymentMethod: '쿠팡',
    notes: '',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP004',
    date: '2026-02-10',
    category: 'F&B',
    itemName: '올베이커리',
    purpose: '판매용 베이커리',
    vendor: '올베이커리',
    supplyAmount: 325091,
    tax: 32509,
    totalAmount: 357600,
    paymentMethod: '카드 결제(온라인)',
    notes: '정기 입고',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP005',
    date: '2026-02-12',
    category: '운영비',
    itemName: '쇼케이스 수리비',
    purpose: '냉장 쇼케이스 수리',
    vendor: '만능수리',
    supplyAmount: 230000,
    tax: 23000,
    totalAmount: 253000,
    paymentMethod: '입금',
    notes: '압축기 교체',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP006',
    date: '2026-02-14',
    category: 'F&B',
    itemName: '프레첼',
    purpose: '판매용 스낵',
    vendor: '쿠팡',
    supplyAmount: 38218,
    tax: 3822,
    totalAmount: 42040,
    paymentMethod: '쿠팡',
    notes: '',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP007',
    date: '2026-02-17',
    category: '운영비',
    itemName: '음향 장비 수리비',
    purpose: '스피커 수리',
    vendor: '사운드프로',
    supplyAmount: 80000,
    tax: 8000,
    totalAmount: 88000,
    paymentMethod: '입금',
    notes: '',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP008',
    date: '2026-02-19',
    category: '운영비',
    itemName: '머그컵',
    purpose: '라운지 비품',
    vendor: '도자기공방',
    supplyAmount: 405000,
    tax: 40500,
    totalAmount: 445500,
    paymentMethod: '입금',
    notes: '로고 각인 50개',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP009',
    date: '2026-02-21',
    category: 'F&B',
    itemName: '빈브라더스',
    purpose: '원두 입고',
    vendor: '빈브라더스',
    supplyAmount: 387000,
    tax: 38700,
    totalAmount: 425700,
    paymentMethod: '입금',
    notes: '정기 입고',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP010',
    date: '2026-02-25',
    category: '운영비',
    itemName: '대창청소비',
    purpose: '환기 덕트 청소',
    vendor: '클린마스터',
    supplyAmount: 300000,
    tax: 30000,
    totalAmount: 330000,
    paymentMethod: '입금',
    notes: '',
    receiptImageUrl: null,
    isPartialCancel: false,
    relatedExpenseId: null,
  },
  {
    id: 'EXP011',
    date: '2026-02-15',
    category: 'F&B',
    itemName: '트레비',
    purpose: '판매용 음료 부분취소',
    vendor: '쿠팡',
    supplyAmount: -37164,
    tax: -3716,
    totalAmount: -40880,
    paymentMethod: '쿠팡',
    notes: '불량품 반품',
    receiptImageUrl: null,
    isPartialCancel: true,
    relatedExpenseId: 'EXP006',
  },
];

export const mockStaffMembers: StaffMember[] = [
  { id: 'STF001', name: '이승훈', defaultShift: 'open', isActive: true },
  { id: 'STF002', name: '김나래', defaultShift: 'middle', isActive: true },
  { id: 'STF003', name: '조하연', defaultShift: 'close', isActive: true },
  { id: 'STF004', name: '이은지', defaultShift: 'open', isActive: true },
  { id: 'STF005', name: '권예지', defaultShift: 'middle', isActive: true },
  { id: 'STF006', name: '황인섭', defaultShift: 'close', isActive: true },
];

export const mockScheduleEntries: ScheduleEntry[] = [
  // 2026-02-01 (일) - 이승훈, 김나래, 조하연 근무 / 이은지, 권예지, 황인섭 휴무
  { id: 'SCH001', staffId: 'STF001', staffName: '이승훈', date: '2026-02-01', shift: 'open', startTime: '08:30', endTime: '17:30', workHours: 9, overtimeHours: 1, notes: '오픈 교육', status: 'confirmed' },
  { id: 'SCH002', staffId: 'STF002', staffName: '김나래', date: '2026-02-01', shift: 'middle', startTime: '11:00', endTime: '20:00', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH003', staffId: 'STF003', staffName: '조하연', date: '2026-02-01', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH004', staffId: 'STF004', staffName: '이은지', date: '2026-02-01', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH005', staffId: 'STF005', staffName: '권예지', date: '2026-02-01', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH006', staffId: 'STF006', staffName: '황인섭', date: '2026-02-01', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-02 (월) - 이승훈, 이은지, 권예지 근무 / 김나래, 조하연, 황인섭 휴무
  { id: 'SCH007', staffId: 'STF001', staffName: '이승훈', date: '2026-02-02', shift: 'open', startTime: '08:30', endTime: '17:30', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH008', staffId: 'STF004', staffName: '이은지', date: '2026-02-02', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH009', staffId: 'STF005', staffName: '권예지', date: '2026-02-02', shift: 'middle', startTime: '11:00', endTime: '20:00', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH010', staffId: 'STF002', staffName: '김나래', date: '2026-02-02', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH011', staffId: 'STF003', staffName: '조하연', date: '2026-02-02', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH012', staffId: 'STF006', staffName: '황인섭', date: '2026-02-02', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-03 (화) - 김나래, 조하연, 황인섭 근무 / 이승훈, 이은지, 권예지 휴무
  { id: 'SCH013', staffId: 'STF002', staffName: '김나래', date: '2026-02-03', shift: 'middle', startTime: '11:00', endTime: '20:00', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH014', staffId: 'STF003', staffName: '조하연', date: '2026-02-03', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH015', staffId: 'STF006', staffName: '황인섭', date: '2026-02-03', shift: 'close', startTime: '14:00', endTime: '22:30', workHours: 8.5, overtimeHours: 0.5, notes: '브랜드 교육 휴관', status: 'confirmed' },
  { id: 'SCH016', staffId: 'STF001', staffName: '이승훈', date: '2026-02-03', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH017', staffId: 'STF004', staffName: '이은지', date: '2026-02-03', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH018', staffId: 'STF005', staffName: '권예지', date: '2026-02-03', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-04 (수) - 이승훈, 권예지, 황인섭, 이은지 근무 / 김나래, 조하연 휴무
  { id: 'SCH019', staffId: 'STF001', staffName: '이승훈', date: '2026-02-04', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH020', staffId: 'STF005', staffName: '권예지', date: '2026-02-04', shift: 'middle', startTime: '11:00', endTime: '19:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH021', staffId: 'STF006', staffName: '황인섭', date: '2026-02-04', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH022', staffId: 'STF004', staffName: '이은지', date: '2026-02-04', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH023', staffId: 'STF002', staffName: '김나래', date: '2026-02-04', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH024', staffId: 'STF003', staffName: '조하연', date: '2026-02-04', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-05 (목) - 김나래, 조하연, 이은지 근무 / 이승훈, 권예지, 황인섭 휴무
  { id: 'SCH025', staffId: 'STF002', staffName: '김나래', date: '2026-02-05', shift: 'middle', startTime: '11:00', endTime: '20:00', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH026', staffId: 'STF003', staffName: '조하연', date: '2026-02-05', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH027', staffId: 'STF004', staffName: '이은지', date: '2026-02-05', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '신규 직원 교육', status: 'confirmed' },
  { id: 'SCH028', staffId: 'STF001', staffName: '이승훈', date: '2026-02-05', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH029', staffId: 'STF005', staffName: '권예지', date: '2026-02-05', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH030', staffId: 'STF006', staffName: '황인섭', date: '2026-02-05', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-06 (금) - 이승훈, 권예지, 조하연, 황인섭 근무 / 김나래, 이은지 휴무
  { id: 'SCH031', staffId: 'STF001', staffName: '이승훈', date: '2026-02-06', shift: 'open', startTime: '08:30', endTime: '17:30', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH032', staffId: 'STF005', staffName: '권예지', date: '2026-02-06', shift: 'middle', startTime: '11:00', endTime: '19:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH033', staffId: 'STF003', staffName: '조하연', date: '2026-02-06', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH034', staffId: 'STF006', staffName: '황인섭', date: '2026-02-06', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH035', staffId: 'STF002', staffName: '김나래', date: '2026-02-06', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH036', staffId: 'STF004', staffName: '이은지', date: '2026-02-06', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },

  // 2026-02-07 (토) - 이승훈, 김나래, 이은지, 황인섭 근무 / 조하연, 권예지 휴무
  { id: 'SCH037', staffId: 'STF001', staffName: '이승훈', date: '2026-02-07', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH038', staffId: 'STF002', staffName: '김나래', date: '2026-02-07', shift: 'middle', startTime: '11:00', endTime: '20:00', workHours: 9, overtimeHours: 1, notes: '', status: 'confirmed' },
  { id: 'SCH039', staffId: 'STF004', staffName: '이은지', date: '2026-02-07', shift: 'open', startTime: '08:30', endTime: '16:30', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH040', staffId: 'STF006', staffName: '황인섭', date: '2026-02-07', shift: 'close', startTime: '14:00', endTime: '22:00', workHours: 8, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH041', staffId: 'STF003', staffName: '조하연', date: '2026-02-07', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
  { id: 'SCH042', staffId: 'STF005', staffName: '권예지', date: '2026-02-07', shift: 'off', startTime: null, endTime: null, workHours: 0, overtimeHours: 0, notes: '', status: 'confirmed' },
];

export const mockAuditLogs: AuditLog[] = [
  { id: 'al1', userId: 'u1', userName: '관리자', action: 'login', target: '시스템', targetId: '', details: '로그인 성공', ipAddress: '192.168.1.100', timestamp: '2026-03-11T09:00:00' },
  { id: 'al2', userId: 'u2', userName: '김매니저', action: 'update', target: '멤버', targetId: 'm1', details: '연락처 변경', previousValue: '010-1234-0000', newValue: '010-1234-5678', ipAddress: '192.168.1.101', timestamp: '2026-03-11T09:15:00' },
  { id: 'al3', userId: 'u3', userName: '이스태프', action: 'read', target: '멤버', targetId: 'm3', details: '멤버 상세 조회', ipAddress: '192.168.1.102', timestamp: '2026-03-11T09:30:00' },
  { id: 'al4', userId: 'u2', userName: '김매니저', action: 'create', target: '예약', targetId: 'r4', details: '워크인 예약 등록', ipAddress: '192.168.1.101', timestamp: '2026-03-11T10:00:00' },
  { id: 'al5', userId: 'u1', userName: '관리자', action: 'download', target: '매출데이터', targetId: '', details: '2026년 2월 매출 데이터 다운로드', ipAddress: '192.168.1.100', timestamp: '2026-03-10T17:00:00' },
];
